ingresses:
  - "https://dp-innsyn.dev.intern.nav.no"
kafka_pool: nav-dev
db_tier: db-custom-1-3840
db_size: 10
db_ha: false
dp_proxy_scope: api://dev-fss.teamdagpenger.dp-proxy/.default
dp_proxy_url: https://dp-proxy.dev-fss-pub.nais.io
dp_soknad:
  url: "http://dp-soknad"
  audience: "dev-gcp:teamdagpenger:dp-soknad"
ny_soknadsdialog:
  ingress: "https://arbeid.dev.nav.no/dagpenger/dialog/soknad"
gammel_soknadsdialog:
  ingress: "https://arbeid.dev.nav.no/soknaddagpenger-innsending"
