ingresses:
  - "https://dp-innsyn.intern.dev.nav.no"
kafka_pool: nav-dev
db_tier: db-custom-1-3840
db_size: 10
db_ha: false
dp_soknad:
  url: "http://dp-soknad"
  audience: "dev-gcp:teamdagpenger:dp-soknad"
ny_soknadsdialog:
  ingress: "https://arbeid.intern.dev.nav.no/dagpenger/dialog/soknad"
gammel_soknadsdialog:
  ingress: "https://arbeid.intern.dev.nav.no/soknaddagpenger-innsending"
wonderwalled: true
