apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-innsyn"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/isalive"
    failureThreshold: 10
    initialDelay: 20
    periodSeconds: 20
    timeout: 5
  readiness:
    path: "/isready"
    failureThreshold: 10
    initialDelay: 20
    periodSeconds: 20
    timeout: 5
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 80
  terminationGracePeriodSeconds: 180
  prometheus:
    enabled: true
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 60m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-dagpenger
        - application: dp-mine-dagpenger-frontend
        - application: dp-soknad
        - application: dp-datadeling
        - application: aia-backend
          namespace: paw
        - application: tokenx-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbound:
      rules:
        - application: dp-soknad
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
  gcp:
    sqlInstances:
      - name: dp-innsyn
        type: POSTGRES_16
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: {{db_ha}}
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        maintenance:
          day: 1
          hour: 4
        databases:
          - name: innsyn
            envVarPrefix: DB
        cascadingDelete: false
  env:
    - name: DP_SOKNAD_URL
      value:  {{dp_soknad.url}}
    - name: DP_SOKNAD_AUDIENCE
      value: {{dp_soknad.audience}}
    - name: NY_SOKNADSDIALOG_INGRESS
      value: {{ny_soknadsdialog.ingress}}
    - name: GAMMEL_SOKNADSDIALOG_INGRESS
      value: {{gammel_soknadsdialog.ingress}}
