apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-innsyn"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/isalive"
    failureThreshold: 10
    initialDelay: 20
    periodSeconds: 20
    timeout: 5
  readiness:
    path: "/isready"
    failureThreshold: 10
    initialDelay: 20
    periodSeconds: 20
    timeout: 5
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  preStopHook:
    http:
      path: /stop
  prometheus:
    enabled: true
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "1000m"
      memory: "2048Mi"
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: dp-dagpenger
        - application: dp-soknad-veileder
        - application: dp-soknad
        - application: paw-auth-proxy
          namespace: paw
        - application: aia-backend
          namespace: paw
    outbound:
      rules:
        - application: dp-soknad
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - name: dp-innsyn
        type: POSTGRES_12
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: {{db_ha}}
        diskSize: {{db_size}}
        diskAutoresize: true
        autoBackupHour: 3
        maintenance:
          day: 1
          hour: 4
        databases:
          - name: innsyn
            envVarPrefix: DB
        cascadingDelete: false
  env:
    - name: DP_PROXY_SCOPE
      value: {{dp_proxy_scope}}
    - name: DP_PROXY_URL
      value: {{dp_proxy_url}}
    - name: DP_SOKNAD_URL
      value:  {{dp_soknad.url}}
    - name: DP_SOKNAD_AUDIENCE
      value: {{dp_soknad.audience}}
    - name: NY_SOKNADSDIALOG_INGRESS
      value: {{ny_soknadsdialog.ingress}}
    - name: GAMMEL_SOKNADSDIALOG_INGRESS
      value: {{gammel_soknadsdialog.ingress}}
