ingresses:
  - "https://dp-innsyn.intern.nav.no"
kafka_pool: nav-prod
db_tier: db-custom-2-7680
db_size: 20
db_ha: true
dp_proxy_scope: api://prod-fss.teamdagpenger.dp-proxy/.default
dp_proxy_url: https://dp-proxy.prod-fss-pub.nais.io
dp_soknad:
  url: "http://dp-soknad"
  audience: "prod-gcp:teamdagpenger:dp-soknad"
ny_soknadsdialog:
  ingress: "https://www.nav.no/dagpenger/dialog/soknad"
gammel_soknadsdialog:
  ingress: "https://tjenester.nav.no/soknaddagpenger-innsending"
