ingresses:
  - "https://dp-innsyn.intern.nav.no"
kafka_pool: nav-prod
db_tier: db-custom-2-7680
db_size: 20
db_ha: true
ny_soknadsdialog:
  ingress: "https://www.nav.no/dagpenger/dialog/soknad"
gammel_soknadsdialog:
  ingress: "https://tjenester.nav.no/soknaddagpenger-innsending"
dp_datadeling:
  perioder_url: "http://dp-datadeling/dagpenger/datadeling/v1/perioder"
  scope: "api://prod-gcp.teamdagpenger.dp-datadeling/.default"
