openapi: 3.0.0
info:
  title: Innsyn API
  version: 1.0.0
  description: API for å forenkle prosessen med å hente informasjon relatert til søknader og vedtak.
  contact:
    name: '#team-dagpenger'
servers:
  - url: https://dp-innsyn.intern.dev.nav.no
    description: dev
  - url: https://dp-innsyn.intern.nav.no
    description: prod
paths:
  /soknad:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Soknad'
          description: OK
      summary: Hent alle søknader
      description: Viser en liste over alle innsendt søknader som er tilknyttet til en spesifikk bruker.
      operationId: get-soknad
      security:
        - tokenX: [ ]
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Soknad'
          description: OK
      summary: Hent alle søknader
      description: Viser en liste over alle innsendt søknader som er tilknyttet til en spesifikk bruker.
      operationId: post-soknad
      security:
        - azure: [ ]


  /vedtak:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vedtak'
          description: OK
      summary: Hent alle vedtak
      description: Viser en liste over alle vedtak som er tilknyttet til en spesifikk bruker.
      operationId: get-vedtak
      security:
        - tokenX: [ ]
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vedtak'
          description: OK
      summary: Hent alle vedtak
      description: Viser en liste over alle vedtak som er tilknyttet til en spesifikk bruker.
      operationId: post-vedtak
      security:
        - azure: [ ]

  /paabegynte:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaabegyntSoknad'
          description: OK
      summary: Hent alle påbegynte søknader
      description: Viser en oversikt over alle søknader som er startet av en bruker.
      operationId: get-paabegynte
      security:
        - tokenX: [ ]

  /behandlingsstatus:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Behandlingsstatus'
          description: OK
      summary: Henter behandlingsstatusen til en søknad.
      description: Viser behandlingsstatusen til en søknad.
      operationId: get-behandlingsstatus
      security:
        - tokenX: [ ]
components:
  schemas:
    Soknad:
      type: object
      required:
        - journalpostId
        - søknadsType
        - kanal
        - datoInnsendt
      properties:
        søknadId:
          type: string
        erNySøknadsdialog:
          type: boolean
        endreLenke:
            type: string
        skjemaKode:
            type: string
        tittel:
            type: string
        journalpostId:
            type: string
        søknadsType:
            type: string
            enum:
              - NySøknad
              - Gjenopptak
        kanal:
            type: string
            enum:
              - Papir
              - Digital
        datoInnsendt:
            type: string
            format: date-time
        vedlegg:
          type: array
          items:
            $ref: '#/components/schemas/Vedlegg'

    Vedlegg:
      type: object
      required:
        - skjemaNummer
        - navn
        - status
      properties:
        skjemaNummer:
          type: string
        navn:
          type: string
        status:
          type: string
          enum:
            - LastetOpp
            - VedleggSendesAvAndre
            - VedleggSendesIkke
            - SendesSenere
            - SendesIkke
            - VedleggAlleredeSendt

    Vedtak:
      type: object
      required:
          - vedtakId
          - fagsakId
          - status
          - datoFattet
          - fraDato
      properties:
        vedtakId:
          type: string
        fagsakId:
          type: string
        status:
          type: string
          enum:
            - INNVILGET
            - AVSLÅTT
            - STANS
            - ENDRING
        datoFattet:
          type: string
          format: date-time
        fraDato:
          type: string
          format: date-time
        tilDato:
            type: string
            format: date-time

    PaabegyntSoknad:
        type: object
        required:
          - søknadId
          - tittel
          - sistEndret
          - erNySøknadsdialog
          - endreLenke
        properties:
          søknadId:
            type: string
          tittel:
            type: string
          sistEndret:
                type: string
                format: date-time
          erNySøknadsdialog:
            type: boolean
          endreLenke:
            type: string

    Behandlingsstatus:
      type: object
      properties:
        behandlingsstatus:
          type: string
          enum:
            - Ukjent
            - FerdigBehandlet
            - UnderBehandling
      required:
        - behandlingsstatus

    DataRequest:
      type: object
      required:
        - personIdent
        - fraOgMedDato
      properties:
        personIdent:
          type: string
          description: Personens fødselsnummer eller D-nummer
        fraOgMedDato:
          type: string
          format: date
          description: Tidligste dato man trenger informasjon. Vedtak som er gyldige på denne dato vil bli med i responsen, selv om de starter tidligere. Vedtak som starter senere enn denne dato vil bli med i responsen hvis de ikke begrenses av tilOgMedDato (se beskrivelse under).
        tilOgMedDato:
          type: string
          format: date
          description: Seneste dato man trenger informasjon. Vedtak som er gyldige på denne dato vil bli med i responsen, selv om de slutter senere. Vedtak med åpen til-dato vil bli med i responsen hvis de er gyldige på gitt tilOgMedDato.

  securitySchemes:
    tokenX:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [TokenX](https://docs.nais.io/security/auth/tokenx/) til autentisering. Du må utveksle IDporten-token
        til et TokenX-token hvor `audience` er satt til `[cluster]:teamdagpenger:dp-innsyn`.
        
        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://wonderwalled-idporten.intern.dev.nav.no/api/obo?aud=dev-gcp:teamdagpenger:dp-innsyn)

    azure:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bruker [Azure AD](https://docs.nais.io/auth/entra-id/) til autentisering.

        For å teste APIet kan du lage et gyldig OBO-token ved å bruke wonderwalled:
        - [dev-gcp](https://azure-token-generator.intern.dev.nav.no/api/obo?aud=dev-gcp:teamdagpenger:dp-innsyn)
  headers: { }
  responses: { }


